export const FIRST_WORK_FILE_LIST = [
    '.editorconfig',
    'images/',
    'images/facebook_color_white.svg',
    'images/feynman.png',
    'images/header-image.png',
    'images/instagram_color_white.svg',
    'images/kaufman-triangle.svg',
    'images/logo_place_footer.svg',
    'images/logo_place_header.svg',
    'images/vk_color_white.svg',
    'index.html',
    'styles/',
    'styles/normalize.css',
    'styles/style.css',
    'texts.md',
];
